on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@773892434931b74bdf54474b73c909779daa9471
    with:
      archive_name: "roBa-firmware-uf2"
